### ISSUE TITLE
ground truth images

### ISSUE THREAD

**Issue by monjoybme** [uci-cbcl/DeepLung#10]
Your study is very impressive. Could you share a link to download ground truth images?

**Comment by wentaozhu** [comment]
LUNA16 dataset https://luna16.grand-challenge.org/data/
LIDC_IDRI dataset https://wiki.cancerimagingarchive.net/display/Public/LIDC-IDRI

**Comment by monjoybme** [comment]
for LUNA16 download link is not working. It will be helpful if you can share ground truth dataset.

**Comment by wentaozhu** [comment]
https://luna16.grand-challenge.org/download/ 

You need to register first to get the dataset. I am sorry that I cannot share the original dataset. Even for the processed dataset, it is too big to share. Try to register first.

**Comment by monjoybme** [comment]
Thanks, by the way, this download link is working [http://academictorrents.com/collection/luna-lung-nodule-analysis-16---isbi-2016-challenge](url).
The dataset contains "annotations.csv" file. Did you extract ground truth images using the .csv file and CT images and after that fed into the deep learning model?

**Comment by wentaozhu** [comment]
You may read the paper to get a general idea of the task https://arxiv.org/pdf/1801.09555.pdf

**Comment by monjoybme** [comment]
Thanks
