### ISSUE TITLE
indent issue

### ISSUE THREAD

**Issue by XuYunqiu** [uci-cbcl/DeepLung#13]
https://github.com/uci-cbcl/DeepLung/blob/58923bab278e5bcf4aeea860a3bef1dd9d3d1462/prepare.py#L443
https://github.com/uci-cbcl/DeepLung/blob/58923bab278e5bcf4aeea860a3bef1dd9d3d1462/prepare.py#L450
https://github.com/uci-cbcl/DeepLung/blob/58923bab278e5bcf4aeea860a3bef1dd9d3d1462/prepare.py#L457

Hi, thanks for share your implementation. 
I got the indent issue when ran the prepare code.
Maybe, the `savenpy` function should be unindent. Is that correct?

**Comment by wentaozhu** [comment]
Thank you so much for your contribution! I have fixed the three indent issues. You may refer to https://github.com/wentaozhu/DeepLung as well.
