### ISSUE TITLE
related to mhd files of luna16 dataset 

### ISSUE THREAD

**Issue by Shrutika994** [uci-cbcl/DeepLung#14]
Hello, I'm getting the following issue. When i download the Luna16 dataset some of mhd files are not present. Did you face the same problem? So the Preprocessing work cannot be carried out. 
Is there any other option to download the luna16 dataset.

**Comment by wentaozhu** [comment]
How about downloading it again? I guess there are some other sources. Please check the issues in the https://github.com/wentaozhu/DeepLung

**Comment by Shrutika994** [comment]
I tried downloading it again, but sadly it did not work so i used the torrents one. Thanks.

**Comment by wentaozhu** [comment]
I guess you have made it. Congratulations!
