### ISSUE TITLE
Is the data use the same as your paper？

### ISSUE THREAD

**Issue by mabihuan** [uci-cbcl/DeepLung#3]
hello，I see your paper just use the LIDC and LUJNA16, but why the code detector/main.py use the DataBowl3?

**Comment by wentaozhu** [comment]
Dear Bihuan,

Thank you very much for your interest!

We used part of code from kaggle data science bowl 2017. And we extended it to the luna16 and nodule classification on LIDC-IDRI with doctors' annotations. We also built a benchmark.

Wentao
