### ISSUE TITLE
The extclsshpinfo.py "find the match from LIDC-IDRI annotation part"， I think there are some mistake

### ISSUE THREAD

**Issue by mabihuan** [uci-cbcl/DeepLung#4]
Dear wentao,

When I read the extclsshpinfo.py, I find the "find the match from LIDC-IDRI annotation part" make some mistake. 

- First，the 71th line in the extclsshpinfo.py，voxcrd[-1] = sliceim.shape[0] - voxcrd[0]，it aim to do filp for z，so I think it should be voxcrd[0] = sliceim.shape[0] - voxcrd[0].

- Second，the 154th~156th lines， voxcrd for z, y, x, but lidcant for x, y, z.  so I think it should be
			dist = math.pow(voxcrd[0] - lidcant[5], 2) # z
			dist += math.pow(voxcrd[1] - lidcant[4], 2) # y
			dist += math.pow(voxcrd[2] - lidcant[3], 2) # x

**Comment by wentaozhu** [comment]
For the second, I think you are right. I have corrected it and now you can get better performance.

For the first, I am very sorry that have forgotten why I used the subtract. Maybe you can check again and if it is wrong again, I will update it.

Thank you very much for the help and interest!

**Comment by mabihuan** [comment]
I run the code modified by voxcrd[0] = sliceim.shape[0] - voxcrd[0] , get the result below , I print the LUNA16 points z,y,x in 1th to 3th column  and LIDC points z,y,x in 4th to 6th column that match. The last column is the mindst.
![_20180615093301](https://user-images.githubusercontent.com/18318866/41446044-e4b32478-707f-11e8-8831-722d56241477.png)

The next is your code voxcrd[-1] = sliceim.shape[0] - voxcrd[0] result.
![_20180615102641](https://user-images.githubusercontent.com/18318866/41447192-a5b74e14-7086-11e8-80b4-44e3903a0133.png)

As you can see the result voxcrd[-1] = sliceim.shape[0] - voxcrd[0] did not get the real match between LUNA16 and LIDC.

**Comment by wentaozhu** [comment]
Thank you very much for the debug information! I have corrected it.

**Comment by mabihuan** [comment]
Dear wentao,

I want to ask you another question base on this code error. According to the error, the label you get for LUNA16 from LIDC will be wrong. Then the result of the nodule classification moudle in your paper DeepLung is wrong.  Can I understand that？

**Comment by wentaozhu** [comment]
Dear Bihuan,

I do not have time to rerun the experiments. But in my first version, I just used the y axis to measure the distance. Maybe it contains some inaccurate cases, but it is not wrong.

Hope you can get better results!

Good luck,
Wentao

**Comment by anruoxi123** [comment]
Did you have the following error running the extclssphinfo.py file?
I hope you can give me some advice!
![afec094bd61851dc4e06f2e176e4af5](https://user-images.githubusercontent.com/43407427/47611925-84140480-daaa-11e8-9556-024394d3dfca.png)

**Comment by CDeepA** [comment]
> Did you have the following error running the extclssphinfo.py file?
> I hope you can give me some advice!
> ![afec094bd61851dc4e06f2e176e4af5](https://user-images.githubusercontent.com/43407427/47611925-84140480-daaa-11e8-9556-024394d3dfca.png)

Hey @anruoxi123 . Did you find a solution to the problem?

**Comment by wentaozhu** [comment]
LIDC-IDRI has more images than LUNA16. Try to remove extra images in LIDC-IDRI.

**Comment by CDeepA** [comment]
Dear wentaozhu. 

Thank you for your help, your were right. An important note,  the folders also had to be renamed after study id and series id.
