### ISSUE TITLE
question about a function in frocwrtdetpepchluna16.py 

### ISSUE THREAD

**Issue by mabihuan** [uci-cbcl/DeepLung#5]
Dear Wentao
 when I run frocwrtdetpepchluna16.py , I find that you get froclist from the function getfrocvalue,
you can see the getfrocvalue function return noduleCADEvaluation's return, but the function
noduleCADEvaluation in noduleCADEvaluationLUNA16 return nothing. So what should
noduleCADEvaluation return ?

**Comment by wentaozhu** [comment]
Could you please provide more information? Thank you very much for your interest!

**Comment by mabihuan** [comment]
I mean in the frocwrtdetpepchluna16.py  153th line you use getfrocvalue function to get the froc value, when I go to see the getfrocvalue function in frocwrtdetpepchluna16.py  116th line, I find  getfrocvalue use the noduleCADEvaluation function to get  froc value in noduleCADEvaluationLUNA16.py 497th line. the question is that noduleCADEvaluation doesn't return anything. So the noduleCADEvaluation function can't return the froc value.

**Comment by wentaozhu** [comment]
You may download a new noduleCADEvaluationLUNA16.py from LUNA16 website. I think it should be easy to fix it.

**Comment by mabihuan** [comment]
I have modified noduleCADEvaluationLUNA16.py， now it work. Thank you.

**Comment by wentaozhu** [comment]
Congratulations! Good luck on your future research!

**Comment by HYB777** [comment]
how did you solve it?  i  met the same problem

**Comment by HYB777** [comment]
@mabihuan how did you solve it? i met the same problem

**Comment by wentaozhu** [comment]
You may get it from #90 #91
