### ISSUE TITLE
about det2cls.py

### ISSUE THREAD

**Issue by anruoxi123** [uci-cbcl/DeepLung#7]
Hello, in det2cls.py file, what is the file resmodelpath = './detcls-'+ STR (fold)+' old/ ckptgbit.t7 '?

I don't show this file here, but when I run the det2cls.py file, it always shows that the file is not found.

Thanks for your advice!

![9db5b1cd42119240770f8f13a9fb41b](https://user-images.githubusercontent.com/43407427/47135027-5e843f80-d2e1-11e8-8f7c-9d2999a58f79.png)
![cd1078b92d760c9df0b2c5a7412ca20](https://user-images.githubusercontent.com/43407427/47135026-5e843f80-d2e1-11e8-9caf-149e2d6f04da.png)

**Comment by wentaozhu** [comment]
How about run the main_nodcls.py file? It seems it is a test script.

**Comment by anruoxi123** [comment]
orry, I didn't run the main_nodcls.py file.

That is to say, after I run the detection code, I want to continue running the classification after detection, I want to run the main_nodcls.py file first, not the det2cls.py file, right?

Is the det2cls.py file the test code for the classification section?

**Comment by anruoxi123** [comment]
Is the preprocesspath path in the main_nodcls.py file the data path after preprocessing?

I added after preprocessing the data path DeepLung - master/the preprocess subset0 /,

I checked that all the files in this path end with clean. Npy, extendbox.npy, label.npy, mask. Npy, origin. Npy, metono.npy, etc.

But the code looks for files ending with -0.npy,

So I always report the following error when I run the main_nodcls.py file. What's the problem?

**Comment by anruoxi123** [comment]
![a985c4b812b18312348069d221aa4b6](https://user-images.githubusercontent.com/43407427/47193023-4ebd3780-d383-11e8-9895-1ccd6a580f69.png)

**Comment by wentaozhu** [comment]
Please take a look at DeepLung/nodcls/data/ to generate data for classification model.

**Comment by anruoxi123** [comment]
Is the classification model after detection using lidc-idri data?

Must the lidc-ldri data be processed with./data/extclsshpinfo.py, humanperformance.py, dimcls.py, nodclsgbit.py, pthumanperformance.py, etc.?

**Comment by wentaozhu** [comment]
Please check the readme carefully.

For nodule classification, first clean the data from LIDC-IDRI. Use the ./data/extclsshpinfo.py to extract nodule labels. humanperformance.py is used to get the performance of doctors.
dimcls.py is used to get the classification based on diameter. nodclsgbt.py is used to get the performance based on GBM, nodule diameter and nodule pixel. pthumanperformance.py is used for patient-level diagnosis performance. kappatest.py is used for kappa value calculation in the paper.
For classification using DPN, use the code in main_nodcls.py. Use the testdet2cls.py to test the trained model. You may revise the code a little bit for different test settings.
For system's classification, that is classification based on detection. First, use the detection's test script in the run_training.sh to get the detected nodules for training CTs. Use the det2cls.py to train the model. And use the testdet2cls.py to test the trained model. You may revise the code a little bit for different test settings.

**Comment by anruoxi123** [comment]
According to my understanding, if it is the classification after running detection, it is necessary to run det2cls.py instead of main_nodcls.py, right?

I would like to ask whether it is necessary to run programs such as./data/extclsshpinfo.py, humanperformance.py, dimcls.py, nodclsgbit.py, pthumanperformance.py before running det2cls.py

**Comment by wentaozhu** [comment]
Yes
