### ISSUE TITLE
About the test results

### ISSUE THREAD

**Issue by anruoxi123** [uci-cbcl/DeepLung#8]
Hello, teacher.

I run before the test, in part due to insufficient memory, I use a total of three figures, run frocwrtdetpepchluna16. Py and noduleCADEvaluationLUNA16 py document gets a result;

Recently, I added all the data, and ran the detection part with ten data again. Running the two files above, I got a result.

Oddly, the results of these two runs are exactly the same. What's causing this?

Thanks for comment!

**Comment by anruoxi123** [comment]
The results of both tests did not produce an image, but the.txt file did.
![9fc2222f155b50ab355f6d71f94cfce](https://user-images.githubusercontent.com/43407427/47356309-3d16bf80-d6f6-11e8-8b6e-26e975bede8d.png)
![88c0785e0d426836ba66fe963cbee01](https://user-images.githubusercontent.com/43407427/47356312-3ee08300-d6f6-11e8-9962-726604181cde.png)

**Comment by wentaozhu** [comment]
Is it the new data or from LUNA16?

**Comment by anruoxi123** [comment]
It is LUNA16.
I just deleted part of the data folder of the test data set on the basis of the original program.
I found that running the frocwrtdetpepchluna16.py file generated the.txt\.png\.csv file was incorrect,

But there is no error in the running process. What is the problem?

**Comment by wentaozhu** [comment]
You must use all the test data. Otherwise, it considers the nodules in other part of test data as missing nodule. Maybe it is the reason for low FROC.

**Comment by anruoxi123** [comment]
When I run the test part of the code, if I test all the data, the program will be stuck in some data, but the GPU display is running all the time.

So after I deleted the data of the test section, I did not have this problem.

So, is the program stuck because of GPU memory?

I only used two gpus.

**Comment by wentaozhu** [comment]
Try to use bigger detection threshold

**Comment by anruoxi123** [comment]
Ok, then I am training again. Thank you very much!

**Comment by anruoxi123** [comment]
Is this threshold size limit?

I went from negative 3 to negative 8, and it's still stuck,

Can I change it to -20?

**Comment by wentaozhu** [comment]
-2, -1, or 0. Please read our paper for details. 
Deeplung: Deep 3d dual path nets for automated pulmonary nodule detection and classification, WACV  2018.

**Comment by anruoxi123** [comment]
Ok, thank you very much!
