### ISSUE TITLE
about LIDC-IDRI data

### ISSUE THREAD

**Issue by anruoxi123** [uci-cbcl/DeepLung#9]
Do you need to filter LIDC data before extracting data labels for LIDC data?

When I run the./data/extclsshpinfo.py file, it always reminds me that I can't find the 000006.dcm file.

Excuse me, why does the program specify 000006.dcm all these pieces?

In some cases, there are no such tablets as 000006.dcm. What should be done in this case?
![e3ec9332aa02803670bed08eb9eb5c0](https://user-images.githubusercontent.com/43407427/47554795-c4557480-d93c-11e8-99bb-2ed020389ed4.png)

**Comment by wentaozhu** [comment]
Yes. We use it to filter LIDC data. If the number of slices is less than 6, we remove the folder.

**Comment by anruoxi123** [comment]
Ok, I've removed the folder with less than 6 files,

But now there's another error. Look at the picture below.

What's the reason?




![d9132313732b1363641f57abec6de7a](https://user-images.githubusercontent.com/43407427/47600774-05ab5a00-d9f9-11e8-9379-f9ed6ee1c6a6.png)

**Comment by anruoxi123** [comment]
![afec094bd61851dc4e06f2e176e4af5](https://user-images.githubusercontent.com/43407427/47601024-f0382f00-d9fc-11e8-9524-fad42831031b.png)

**Comment by abhishek-s-jha** [comment]
antdictscan maps LIDC parent folder with final folder which contains CT scans in that folder.
eg: antdictscan{'0380_3000012-34623' : some list of values}

And code is searching for this structure:
antdictscan{'0380_SeriesInstanceUID': list of values}

Modify line 135 in extclsshpinfo.py:
antdictscan[pid+'\_'+srs] = v --> antdictscan[pid + '\_' + RefDs[0x20, 0x0e].value] = v
**RefDs[0x20, 0x0e].value contain SeriesInstanceUID of CT present in folder LIDC-IDRI-0380

https://github.com/uci-cbcl/DeepLung/blob/58923bab278e5bcf4aeea860a3bef1dd9d3d1462/nodcls/data/extclsshpinfo.py#L135
